name: Python Flask Docker Build
 
on:
  push:
    branches:
      - main  # Adjust the branch as needed
 
jobs:
  build:
    runs-on: self-hosted 
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
 
    - name: Cleanup
      run: |
        docker stop flask || true
        docker rm flask || true
        docker image prune -af || true
        
    - name: Build Docker Image
      run: |
        imageName="python/flask:${GITHUB_RUN_NUMBER}"
        docker build -t $imageName .
        
    - name: Run Docker Container
      run: |
        docker run --name flask -d -p 5000:5000 python/flask:${GITHUB_RUN_NUMBER}
        
    - name: Scribe tool install
      id: scribe_install
      uses: scribe-security/action-installer@master
      with:
        tools: valint
      run: sudo bash -e -c "source $HOME/.scribe/scribe-tool/valint/1.0.0/activate"

