name: Python Flask Docker Build
 
on:
  push:
    branches:
      - main  # Adjust the branch as needed
 
jobs:
  build:
    runs-on: self-hosted 
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
 
    - name: Cleanup
      run: |
        docker stop flask || true
        docker rm flask || true
        docker image prune -af || true
    - name: Build Docker Image
      run: |
        imageName="python/flask:${GITHUB_RUN_NUMBER}"
        docker build -t $imageName .
    - name: Run Docker Container
      run: |
        docker run --name flask -d -p 8080:8080 python/flask:${GITHUB_RUN_NUMBER}
